experiment_id: sep_motion_batchnorm_start_encoder
experiment: stochasticmotion
model_save_dir: data/models
num_workers: 12
max_frames: 5
split: 0.5
split_direction: samples
loss: perceptual #reconstruction or perceptual
watch_gradients: True
logging:
  video: True
  n_fvd_samples: 1000
  n_samples: 20
  bs_i3d: 8

d_t:
  use: True
  patch_temp_disc: False
  gp_weight: 1.2
  fmap_weight: 1.
  gen_weight: 1.
  bce_loss: False
  num_classes: 1
  after_epoch: 10
  max_frames: 12
  gp_1: False

loss_weights:
  l1: 0.0
  l2: 0.2
  kld: 1.0
  vgg: 0.8
  moments_constraint: 0.0
  gan: 1.0

latent_dimensions:
  pq_latent_size: 32 # Double the size is the latent output of hamiltonian unet

# Define networks architectures
networks:
  variational: True
  dtype : "float"
  start_encoder:
    type: "standard"
    hidden_conv_layers: 2
    n_filters: [ 8, 12, 32 ]  # first + hidden
    kernel_sizes: [ 3, 3, 3, 3, 3]  # first + hidden + last
    strides: [ 1, 2, 2, 2, 2]  # first + hidden + last
    out_channels: 32 # TODO: Evaluate impact

  motion_encoder:
    ENC_M_channels: [ 64, 128, 128, 256, 256 ]
    z_dim: 2048
    img_size: 64

  gru:
    input_size: 32
    hidden_sizes: 32 #[32, 32, 32, 32]
    kernel_sizes: 3 #[3, 3, 3, 3]
    n_layers: 1

  decoder:
    n_residual_blocks: 3
    n_filters: [32, 16, 8]
    kernel_sizes: [3, 3, 3, 3]

# Define HGN Integrator torch.Size([2, 16, 9, 9]) torch.Size([2, 3, 72, 72]) torch.Size([1, 48, 72, 72]) torch.Size([1, 3, 72, 72])
integrator:
  method: "Leapfrog"

# Define optimization
optimization:
  epochs: 60
  precision: 16
  batch_size: 16
  test_batch_size: 16
  input_frames: 13  # Number of frames to feed to the encoder while training
  # Learning rates
  hnn_lr: 1.5e-4
  decoder_lr: 1.5e-4
  frame_encoder_lr: 1.5e-4
  motion_encoder_lr: 1.5e-4
  disc_t_lr: 1.5e-4
  training_objective: 'prior' # { prior, posterior }

# Define data characteristics
dataset:
  datakeys: ['images'] #['sequence']
  name: 'Bair' #'Bair' #'Human36mDataset'
  aug: False
  crop_to_size: 128
  data_path_local: /home/sd/Documents/thesis/hgn_natural/data/bair/bair/
  data_path: /export/scratch/compvis/datasets/bair/
  img_size: 64
  split: official
  sequence_length: 30
  spatial_size: !!python/tuple [64, 64]
  radius_bound: 'auto'
  rollout:
    delta_time: 0.125
    n_channels: 3
    noise_level: 1  # Level of environment noise. 0 means no noise, 1 means max noise.
                    # Maximum values are defined in each environment.
